name: Publish documentation

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout main
        uses: actions/checkout@v4

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          SITE_NAME: "Doctrine Diagram Bundle ${{ github.event.release.tag_name }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
