name: Bundle install

on:
  pull_request:

jobs:
  sy70:
    strategy:
      matrix:
        sf: [ '7.0.*' ]
        php: [ '8.2','8.3','8.4','8.5' ]
        composer-flag: [ '--prefer-lowest', '--ansi' ]
    uses: jawira/doctrine-diagram-bundle/.github/workflows/install-bundle.yaml@update-ga
    with:
      symfony: ${{ matrix.sf }}
      php: ${{ matrix.php }}
      composer-flag: ${{ matrix.composer-flag }}

  sy80:
    strategy:
      matrix:
        sf: [ '8.0.*' ]
        php: [ '8.4' , '8.5' ]
        composer-flag: [ '--prefer-lowest', '--ansi' ]
    uses: jawira/doctrine-diagram-bundle/.github/workflows/install-bundle.yaml@update-ga
    with:
      symfony: ${{ matrix.sf }}
      php: ${{ matrix.php }}
      composer-flag: ${{ matrix.composer-flag }}
