name: Quality assurance

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  qa:
    strategy:
      matrix:
        php: [ '8.1','8.2','8.3','8.4' ]
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          coverage: xdebug
          tools: phing:v3

      - uses: actions/checkout@v4

      - name: composer:install
        run: phing composer:install

      - name: composer:validate
        run: phing composer:validate

      - run: echo "PHP_CS_FIXER_IGNORE_ENV=yes" >> "$GITHUB_ENV"
      - name: cs:check
        run: phing cs:check

      - name: phpstan:analyse
        run: phing phpstan:analyse

      - name: composer:audit
        run: phing composer:audit
